#!/bin/bash

# Ghost import script
# This script provides instructions for importing Hugo content to Ghost

echo "=== Ghost Content Import Instructions ==="
echo ""
echo "The migration has generated a ghost-import.json file with your Hugo content."
echo ""
echo "To import this content into Ghost:"
echo ""
echo "1. Access your Ghost Admin panel:"
echo "   - For local development: http://localhost:2368/ghost/"
echo "   - For production: https://cybermonkey.net.au/blog/ghost/"
echo ""
echo "2. Navigate to Settings → Migration → Import content"
echo ""
echo "3. Upload the ghost-import.json file"
echo ""
echo "4. Ghost will import all posts, pages, and tags"
echo ""
echo "Note: The import includes:"
echo "  - 22 posts/pages converted from Hugo"
echo "  - All tags and categories"
echo "  - Draft status preserved"
echo "  - Author information"
echo ""
echo "After import, you may need to:"
echo "  - Configure navigation menu"
echo "  - Set up redirects for old URLs"
echo "  - Upload images separately"
echo "  - Review and publish draft content"
echo ""
echo "File location: $(pwd)/ghost-import.json"