version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 10
    reviewers:
      - "CodeMonkeyCybersecurity/dev-team"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"
      include: "scope"
    pull-request-branch-name:
      separator: "-"
    ignore:
      # Ignore major version updates for stable packages
      - dependency-name: "hugo-*"
        update-types: ["version-update:semver-major"]
    groups:
      # Group all non-security npm updates together
      development-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
        exclude-patterns:
          - "eslint*"
          - "stylelint*"
          - "prettier*"
      linting:
        patterns:
          - "eslint*"
          - "stylelint*"
          - "prettier*"

  # Enable version updates for Go modules
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "go"
    commit-message:
      prefix: "go"
      include: "scope"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable security updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"