baseURL = 'https://cybermonkey.net.au'
languageCode = 'en-us'
title = 'Code Monkey Cybersecurity'

# Optional: better URLs
canonifyURLs = true
enableRobotsTXT = true

# Optional: use clean URLs (no .html)
uglyURLs = false

# Optional: build config
buildDrafts = false
buildFuture = false
buildExpired = false

# Site-wide metadata
[params]
  author = "Henry Oliver"
  description = "Cybersecurity with Humans. Managed XDR, backup, DevSecOps, and open source tools from Fremantle."
  keywords = ["Cybersecurity", "XDR", "SIEM", "Penetration Testing", "Backup", "Open Source", "Australia"]
  contact_email = "main@cybermonkey.net.au"
  umami_script = "https://u.cybermonkey.dev/script.js"
  umami_site_id = "970ff30a-ab5d-4c66-8f77-55cafc76083c"
  assetDir = "assets"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

# Optional: social links
[social]
  github = "https://github.com/CodeMonkeyCybersecurity"
  facebook = "https://facebook.com/codemonkeycyber"
  twitter = "https://x.com/codemonkeycyber"

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.Robots]
mediaType = "text/plain"
baseName = "robots"
isPlainText = true
notAlternative = true

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isPlainText = true

# Optional: default settings for content
[markup]
  [markup.goldmark.renderer]
    unsafe = true  # Allow inline HTML in markdown

# Optional: default frontmatter for new pages
[frontmatter]
  date = ["lastmod", ":git", "date"]