baseURL = 'https://cybermonkey.net.au'
languageCode = 'en-us'
title = 'Code Monkey Cybersecurity'

# Optional: better URLs
canonifyURLs = true
enableRobotsTXT = true

# Optional: use clean URLs (no .html)
uglyURLs = false

# Optional: build config
buildDrafts = false
buildFuture = false
buildExpired = false

# Output formats for search - moved to end of file

# Hugo Book theme removed - using native layouts

# Site-wide metadata
[params]
  author = "Henry Oliver"
  description = "Cybersecurity. With Humans. Managed XDR, backup, DevSecOps, and open source tools from Fremantle."
  keywords = ["Cybersecurity", "XDR", "SIEM", "Penetration Testing", "Backup", "Open Source", "Australia"]
  contact_email = "main@cybermonkey.net.au"
  umami_script = "https://u.cybermonkey.dev/script.js"
  umami_site_id = "970ff30a-ab5d-4c66-8f77-55cafc76083c"
  assetDir = "assets"
  enableGitInfo = true
  Logo = 'favicon.png'
  
  # Content organization
  mainSections = ["posts", "resources"]
  paginate = 12
  rssLimit = 20
  
  # Development helpers
  enableRobotsTXT = true
  enableEmoji = true
  
  # Related content configuration
  related_posts = true
  
  # SEO and Social Media
  images = ["images/cover_puppy_moni_monkey_optimized.jpg"]
  twitter_site = "@codemonkeycyber"
  facebook_admins = "codemonkeycyber"
  
  # Business Information
  business_name = "Code Monkey Cybersecurity"
  business_type = "Technology Company"
  address_locality = "Fremantle"
  address_region = "WA"
  address_country = "Australia"
  postal_code = "6160"
  phone = "+61432038310"
  abn = "77 177 673 061"
  
  # Geographic targeting
  geo_region = "AU-WA"
  geo_placename = "Fremantle, Western Australia"
  geo_position = "-32.0569;115.7439"
  ICBM = "-32.0569;115.7439"

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

# Navigation now uses auto-discovery - configuration removed

[menu]

# Main navigation menu (for desktop header)
[[menu.main]]
name = "Services"
url = "/offerings/"
weight = 10

[[menu.main]]
name = "Resources"
url = "/resources/"
weight = 20
hasChildren = true

  [[menu.main]]
  parent = "Resources"
  name = "Documentation"
  url = "/resources/"
  weight = 21

  [[menu.main]]
  parent = "Resources"
  name = "Education"
  url = "/resources/education/"
  weight = 22

[[menu.main]]
name = "About"
url = "/about-us/"
weight = 30

[[menu.main]]
name = "Blog"
url = "/blog/"
weight = 40

# Before menu (appears at top of left sidebar) - removed to avoid duplication

# Resources section
[[menu.resources]]
name = "Documentation"
url = "/resources/"
weight = 10

[[menu.resources]]
name = "Education"
url = "/resources/education/"
weight = 12

# About Us section
[[menu.about]]
name = "About Us"
url = "/about-us/"
weight = 10

[[menu.about]]
name = "Contact"
url = "/about-us/contact/"
weight = 15

[[menu.about]]
name = "Governance"
url = "/about-us/governance/"
weight = 20

[[menu.about]]
name = "Customer Login"
url = "/about-us/customer-login/"
weight = 25

# Blog section
[[menu.blog]]
name = "Blog"
url = "/blog/"
weight = 10

# Platform/Training menus removed - now using auto-discovery

# External links (External section)
[[menu.after]]
name = "Github"
url = "https://github.com/CodeMonkeyCybersecurity"
weight = 10

# Theme reference removed - using native Hugo layouts

[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"

# Social links moved to params
[params.social]
  github = "https://github.com/CodeMonkeyCybersecurity"
  facebook = "https://facebook.com/codemonkeycyber"
  instagram = "https://instagram.com/code_monkey_cyber"
  linkedin = "https://linkedin.com/company/codemonkeycyber"

[outputs]
home = ["HTML", "RSS", "JSON"]
page = ["HTML"]
section = ["HTML", "RSS"]

[outputFormats.Robots]
mediaType = "text/plain"
baseName = "robots"
isPlainText = true
notAlternative = true

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isPlainText = true

# Enhanced markup configuration
[markup]
  [markup.goldmark.renderer]
    unsafe = true
    hardWraps = false
    xhtml = false
  [markup.goldmark.extensions]
    attribute = true
    autoHeadingID = true
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.parser]
    autoHeadingIDType = "github"
    wrapStandAloneImageWithinParagraph = false
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 4
    ordered = false
  [markup.highlight]
    style = "github"
    lineNos = true
    lineNumbersInTable = false
    noClasses = false
    codeFences = true
    guessSyntax = true

# Optional: default frontmatter for new pages
[frontmatter]
  date = ["lastmod", ":git", "date"]

# Performance optimizations
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  [minify.tdewolff.html]
    keepDefaultAttrVals = false
    keepDocumentTags = true
    keepEndTags = true
    keepQuotes = false
    keepWhitespace = false

# Image processing optimization
[imaging]
  quality = 85
  resampleFilter = "Lanczos"
  anchor = "Smart"
  bgColor = "#ffffff"
  hint = "photo"
  
  # Default image processing options
  [imaging.exif]
    includeFields = ""
    excludeFields = "GPS|Orientation"
    disableDate = false
    disableLatLong = true

# Enhanced caching configuration
[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "168h"  # 1 week for images
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "72h"   # 3 days for CSS/JS
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = "168h"  # 1 week for modules
  [caches.getjson]
    dir = ":cacheDir/:project"
    maxAge = "24h"
  [caches.getcsv]
    dir = ":cacheDir/:project"
    maxAge = "24h"

# Related content configuration
[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
    name = "keywords"
    weight = 100
  [[related.indices]]
    name = "tags"
    weight = 80
  [[related.indices]]
    name = "categories"
    weight = 60
  [[related.indices]]
    name = "section"
    weight = 40

# Taxonomies
[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

# Privacy configuration
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = false
    simple = true
  [privacy.x]
    disable = false
    enableDNT = true
    simple = true
  [privacy.vimeo]
    disable = false
    enableDNT = true
    simple = true
  [privacy.youtube]
    disable = false
    privacyEnhanced = true
