baseURL = 'https://cybermonkey.net.au'
languageCode = 'en-us'
title = 'Code Monkey Cybersecurity'

# Optional: better URLs
canonifyURLs = true
enableRobotsTXT = true

# Optional: use clean URLs (no .html)
uglyURLs = false

# Optional: build config
buildDrafts = false
buildFuture = false
buildExpired = false

[module]
[[module.imports]]
  path = "github.com/alex-shpak/hugo-book"

# Site-wide metadata
[params]
  author = "Henry Oliver"
  description = "Cybersecurity. With Humans.. Managed XDR, backup, DevSecOps, and open source tools from Fremantle."
  keywords = ["Cybersecurity", "XDR", "SIEM", "Penetration Testing", "Backup", "Open Source", "Australia"]
  contact_email = "main@cybermonkey.net.au"
  umami_script = "https://u.cybermonkey.dev/script.js"
  umami_site_id = "970ff30a-ab5d-4c66-8f77-55cafc76083c"
  assetDir = "assets"
  enableGitInfo = true
  BookLogo = 'favicon.png'

[languages]
[languages.en]
  languageName = 'English'
  contentDir = 'content'
  weight = 1

[menu]
# Main navigation menu
[[menu.main]]
name = "Documentation"
url = "/docs/"
weight = 10

[[menu.main]]
name = "Blog"
url = "/posts/"
weight = 15

[[menu.main]]
name = "About"
url = "/docs/governance/"
weight = 20

# Platform dropdown menu
[[menu.platform]]
name = "Delphi Notify"
url = "/docs/delphi/"
weight = 10
[menu.platform.params]
description = "XDR Security Platform"

[[menu.platform]]
name = "Backup Services"
url = "/docs/delphi/backup/"
weight = 20
[menu.platform.params]
description = "Data Protection"

[[menu.platform]]
name = "Pen Testing"
url = "/docs/delphi/penetration-testing/"
weight = 30
[menu.platform.params]
description = "Security Assessment"

# Training dropdown menu
[[menu.training]]
name = "Scam Education"
url = "/docs/training/"
weight = 10
[menu.training.params]
description = "Protect against fraud"

[[menu.training]]
name = "Phishing Training"
url = "/docs/training/phishing/"
weight = 20
[menu.training.params]
description = "Email security awareness"

# Footer menu (legacy)
[[menu.after]]
name = "Github"
url = "https://github.com/CodeMonkeyCybersecurity"
weight = 10

[[menu.after]]
name = "Theme"
url = "https://themes.gohugo.io/themes/hugo-book/"
weight = 20

[sitemap]
  changefreq = "weekly"
  priority = 0.7
  filename = "sitemap.xml"

# Optional: social links
[social]
  github = "https://github.com/CodeMonkeyCybersecurity"
  facebook = "https://facebook.com/codemonkeycyber"
  instagram = "..."
  linkedin = "..."

[outputs]
home = ["HTML", "RSS", "JSON"]

[outputFormats.Robots]
mediaType = "text/plain"
baseName = "robots"
isPlainText = true
notAlternative = true

[outputFormats.JSON]
mediaType = "application/json"
baseName = "index"
isPlainText = true

# Optional: default settings for content
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    attribute = true
  [markup.tableOfContents]
    startLevel = 1

# Optional: default frontmatter for new pages
[frontmatter]
  date = ["lastmod", ":git", "date"]

# Performance optimizations
[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  [minify.tdewolff.html]
    keepDefaultAttrVals = false
    keepDocumentTags = true
    keepEndTags = true
    keepQuotes = false
    keepWhitespace = false

# Image processing optimization
[imaging]
  quality = 85
  resampleFilter = "Lanczos"
  anchor = "Smart"

# Caching configuration
[caches]
  [caches.images]
    dir = ":resourceDir/_gen"
    maxAge = "24h"
  [caches.assets]
    dir = ":resourceDir/_gen"
    maxAge = "24h"
  [caches.modules]
    dir = ":cacheDir/modules"
    maxAge = "24h"
