services:
  ghost:
    image: ghost:5-alpine
    restart: unless-stopped
    container_name: ghost-cms
    ports:
      - "2368:2368"
    environment:
      # Use production mode for proper URL handling
      NODE_ENV: production
      # Use default database location
      database__client: sqlite3
      # Site configuration - update this to your production URL
      url: ${GHOST_URL:-https://cybermonkey.net.au/blog}
      # Logging
      logging__level: info
      logging__transports: '["stdout"]'
      # Admin URL configuration
      admin__url: ${GHOST_ADMIN_URL:-https://cybermonkey.net.au/blog}
    volumes:
      # Single volume for all Ghost data
      - ghost-data:/var/lib/ghost/content
      # Custom themes
      - ./themes:/var/lib/ghost/content/themes
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2368/ghost/api/admin/site/"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 60s  # Give more time to start

volumes:
  ghost-data:

networks:
  default:
    name: ghost-network
    