version: '3.8'

services:
  ghost:
    image: ghost:5-alpine
    container_name: ghost-cms
    restart: unless-stopped
    ports:
      - "8009:2368"
    environment:
      # Basic Ghost configuration
      NODE_ENV: production
      
      # URL configuration - update this for local testing
      url: ${GHOST_URL:-http://localhost:8009}
      
      # Mail configuration for Mailcow
      mail__transport: SMTP
      mail__options__host: ${MAIL_HOST}
      mail__options__port: ${MAIL_PORT}
      mail__options__secure: ${MAIL_SECURE}
      mail__from: ${MAIL_FROM}
      mail__options__auth__user: ${MAIL_USER}
      mail__options__auth__pass: ${MAIL_PASSWORD}
    
    volumes:
      # Persistent volume for Ghost data (content + SQLite database)
      - ghost-data:/var/lib/ghost/content
    
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:2368/ghost/api/admin/site/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

volumes:
  ghost-data:
    driver: local