# docker-compose.yaml
version: '3.8'

services:
  helen:
    image: nginx:alpine
    container_name: helen
    
    # Security: Run as non-root user
    user: "nginx:nginx"
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
        reservations:
          memory: 64M
          cpus: '0.25'
    
    # Read-only root filesystem for security
    read_only: true
    
    volumes:
      - ./public:/usr/share/nginx/html:ro # Shared webroot for validation
      - /tmp # Writable temp directory
      - /var/cache/nginx # Writable cache directory
      - /var/run # Writable runtime directory
    
    ports:
      - "8009:80"
    
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
    # Restart policy
    restart: unless-stopped
    
    # Environment variables
    environment:
      - NGINX_WORKER_PROCESSES=1
      - NGINX_WORKER_CONNECTIONS=1024