apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helen-dev
  namespace: development
  labels:
    app: helen-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helen-dev
  template:
    metadata:
      labels:
        app: helen-dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: role
                operator: In
                values:
                  - backend
      containers:
      - name: helen-dev
        image: chickenj0/helen-dev:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: helen-dev-service
  namespace: development
spec:
  selector:
    app: helen-dev
  ports:
  - protocol: TCP
    port: 80          # Port for the service
    targetPort: 80    # Port on the pod
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helen-dev-ingress
  namespace: development
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - cybermonkey.dev
    secretName: tls-cybermonkey-dev
  rules:
  - host: cybermonkey.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: helen-dev-service
            port:
              number: 80
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: mail@cybermonkey.dev
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: public