# docker-compose.yaml
services:
  nginx:
    image: nginx
    container_name: helen-prod
    volumes:
      - ./:/usr/share/nginx/html:ro # Shared webroot for validation
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Custom NGINX configuration
    ports:
      - "8009:80"
    restart: always
