---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helen-sh-ingress
  namespace: sh
spec:
  rules:
  - host: cybermonkey.sh
    http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: helen-sh-service
                port:
                  number: 80